language: python
python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
  - 3.7
script: nosetests tests
install:
  - pip install -r requirements.txt
  - pip install -r test_requirements.txt
notifications:
  email: false
